/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Dialogos;

/**
 *
 * @author israe
 */
public class DialogoConfirmarGUI extends javax.swing.JFrame {

    /**
     * Creates new form DialogoConfirmarGUI
     */
    public DialogoConfirmarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jpContainer.setBackground(new java.awt.Color(237, 237, 237));
        jpContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(44, 44, 44));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 44, 44));
        jLabel2.setText("Deseas continuar?");
        jpContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 20));

        btnValidar.setBackground(new java.awt.Color(0, 117, 250));
        btnValidar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Check.png"))); // NOI18N
        btnValidar.setText("Validar");
        btnValidar.setBorder(null);
        btnValidar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnValidar.setPreferredSize(new java.awt.Dimension(115, 40));
        jpContainer.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 100, 40));

        btnCancelar.setBackground(new java.awt.Color(250, 76, 76));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/X.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar.setPreferredSize(new java.awt.Dimension(115, 40));
        jpContainer.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpContainer;
    // End of variables declaration//GEN-END:variables
}
